deployment:
  tasks:
    - export APPPATH=/home/agxservice/public_html/api.agxservice.work.gd
    - /bin/cp -R src $APPPATH/
    - /bin/cp package.json $APPPATH/
    - /bin/cp package-lock.json $APPPATH/
    - /bin/mkdir -p $APPPATH/tmp
    - /bin/touch $APPPATH/tmp/restart.txt